// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpgajrzpglvxxnynyknq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZ2FqcnpwZ2x2eHhueW55a25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTc4MDYsImV4cCI6MjA2NTQ3MzgwNn0.8I20a4MND1FZlcwTH7GKDMFKV-D9F19N_ajiFphHNTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);